name: eff_algo
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11.2
  - cxx-compiler=1.6.0
  - openjdk=17.0.10